### ISSUE TITLE
No need to wait after Wire.requestFrom().

### ISSUE THREAD

**Issue by Koepel** [GreenGhostMan/chefbot#1]
You may remove all the `while(Wire.available()<6);` after a `Wire.requestFrom()` in the files:
- chefbot/chefbot_bringup/Arduino/motor_controller_pid_imu/imu.ino
- chefbot/chefbot_bringup/Arduino/motor_controller_pid_imu_cmdMessenger/imu.ino

Explanation: [Common-mistakes#1](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes#1)

**Comment by ROM-robotics** [comment]
Thank you! Koepel
